### PR TITLE
Fix isPresentWait and Remove support for JitPack

### LINKED ISSUE #128: [BUG] version 0.19.0 failed to build for Jitpack
## The problem
When publishing on jitpack, version 0.19.0 failed.
https://jitpack.io/#willowtreeapps/conductor-mobile
```
Build starting...
Start: Fri Aug 30 18:55:10 UTC 2019 e273148adafd
Git:
0.19.0-0-g11ae006
commit 11ae006b23a422cd6bcccaefb7cc815951676e36
Merge: 493a08d bc21e26
Author: Mark Han 
Date:   Tue Aug 27 12:02:42 2019 -0400

    Merge branch 'master' into release/0.19.0

Running install command:
./gradlew assemble publishToMavenLocal
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Build tool exit code: 0
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Looking for pom.xml in build directory and ~/.m2
2019-08-30T18:55:13.819712695Z
Exit code: 0

ERROR: No build artifacts found
```

### LINKED ISSUE #129: [BUG] isPresentWait should use visibilityOfAllElementsLocatedBy
## The problem

In the `0.19.0` release, `isPresentWait` was refactored to begin using the `presenceOfAllElementsLocatedBy` method. Unfortunately, this changes the behavior of `isPresentWait`.

In certain cases, elements can exist and be invisible (or not on the screen) and would return true with the new method.

To avoid this issue, we should use `visibilityOfAllElementsLocatedBy` instead.

We could also just refactor the method again to do something else...

## Environment

* Conductor-Mobile Version: 0.19.0
* Last Conductor-Mobile version that did not exhibit the issue (if applicable): 0.18.0
* Desktop OS/version used to run Conductor-Mobile:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* `appium-doctor` results are passing []:

## Details

Also to keep in mind, this is a hypothetical problem that I haven't seen yet, but am anticipating when/if people start upgrading.

## Link to Appium/Conductor-Mobile logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Stacktrace, Appium logs, and `config.yaml` contents. Link them here.
Do _NOT_ paste your full logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Relevant logs, please!

## Code To Reproduce Issue [ Good To Have ]
```
public boolean isPresentWait(By by, long timeOutInSeconds) {
        waitForCondition(presenceOfAllElementsLocatedBy(by), timeOutInSeconds, 500);
        return isPresent(by);
    }
```

```
public boolean isPresentWait(By by, long timeOutInSeconds) {
        waitForCondition(visibilityOfAllElementsLocatedBy(by), timeOutInSeconds, 500);
        return isPresent(by);
    }
```

### PR DESCRIPTION
**Pull request by aaron-goff**
Fix isPresentWait
- add exception handling for when element is not found
- change to search for visibility instead of presence
Delete jitpack.yaml
-  remove support for jitpack

### Related Issue

closes #128 - we are retiring support for jitpack in favor of maven central
closes #129

### Description
- Removed the `jitpack.yaml` file which should signal the end of the jitpack support. We will need to note these in the 0.19.1 release notes
- Fixed a few issues with the new version of `isPresentWait`
-- Added exception handling for when the element isn't found, so that we can return a `false` value
-- Swapped out `presenceOf`... for `visibilityOf`..., as there are a _few_ times where an element will exist but not be visible (main example is iOS modal presentations)

### Additional Info
Shoutout @evant for helping with the exception stuff
Shoutout @mrk-han for helping with the jitpack stuff

Also if anyone has extra information about retiring jitpack, just let me know
### Checklist

* [x] Have you added an explanation of what your changes do?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

File: src/main/java/com/joss/conductor/mobile/Locomotive.java [hunk 1]
```diff
@@ -314,8 +310,12 @@ public boolean isPresentWait(String id, long timeOutInSeconds) {
     }
 
     public boolean isPresentWait(By by, long timeOutInSeconds) {
```
Comment (bglazierjr) [inline src/main/java/com/joss/conductor/mobile/Locomotive.java]: Perhaps increase the flexibility of this method by allowing for chaining of selectors. Not sure of the exact syntax but something like this:
```
public boolean isPresentWait(By... selectors, long timeOutInSeconds) {
  try {
       for (By selectors : selector) {
            waitForCondition(visibilityOfAllElementsLocatedBy(selector), timeOutInSeconds, 500);
       }
   } catch (TimeoutException e) {
        return false;
   }
}
```

Comment (aaron-goff) [reply src/main/java/com/joss/conductor/mobile/Locomotive.java]: I don't think I'll have time to test these changes out. Would you mind making a feature request?
(Just being a little paranoid with how late we figured out the actual behavior of `isPresentWait` had changed)

Comment (mrk-han) [reply src/main/java/com/joss/conductor/mobile/Locomotive.java]: I don't think chaining is needed. If wanted then feature request would be nice.

If there is a good use-case for chaining, and will increase your QOL then a feature request would be awesome

Comment (bglazierjr) [reply src/main/java/com/joss/conductor/mobile/Locomotive.java]: It is more about convenience than need and increased flexibility. Just eliminates the need to re-type `getDriver().isPresentWait()` over and over. I'm not super passionate about it, especially since I no longer am a consumer of this conductor-mobile so it was just a "while you are already in there" type idea.
