### PR TITLE
Fix swipe lengths

### LINKED ISSUE #81: swipeCenterLong and swipeCenterSuperLong will swipe the same distance for UP and LEFT cases
In the performSwipe function:

`case UP:`
                    `int toYUp = (int) (from.getY() - (screen.getHeight() * percentage));`
                    `toYUp = toYUp <= 0 ? 1 : toYUp; // toYUp cannot be less than 0`

For example:
swipeCenter percentage = .25
swipeCenterLong percentage = .5
swipeCenterSuperLong percentage = 1.0

so based on a 100 pixel screen:
from.getY() = 50
getHeight() = 100

toYUP = 50 - (100 * .5)

toYUP will always equal 0 or less for Long and SuperLong variants and then be set to 1 in the next line

### PR DESCRIPTION
**Pull request by aaron-goff**
### Related Issue
closes #81 
### Description
Implemented changes to change swipe lengths and their associated unit tests

Also some minor README stuff I saw

### Checklist

* [x] Have you added an explanation of what your changes do?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

File: src/main/java/com/joss/conductor/mobile/Locomotive.java [hunk 1]
```diff
@@ -800,7 +800,7 @@ private Locomotive performSwipe(SwipeElementDirection direction, boolean isLongP
         if (direction != null) {
             switch (direction) {
                 case UP:
-                    int toYUp = (int) (from.getY() - (screen.getHeight() * percentage));
+                    int toYUp = (int) (from.getY() - (from.getY() * percentage));
```
Comment (evant) [inline src/main/java/com/joss/conductor/mobile/Locomotive.java]: Going to take your word that this math is correct.

**Comment by mrk-han** [comment]
And thanks @nerdsosky for the issue
